Added Vector store for PGVector
Knowly-ai/langtorch pull request #134
Opened 2023-06-16 14:28 UTC by AyoTheDev

2023-06-17 05:16 UTC, li2109 commented
> Kudos, SonarCloud Quality Gate passed!    [![Quality Gate passed](https://camo.githubusercontent.com/e4a90cf346b46d44c5652111d68603714bfb7693043d07a95992de3a30bfce04/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f7061737365642d313670782e706e67)](https://sonarcloud.io/dashboard?id=Knowly-ai_langtorch&pullRequest=134)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=Knowly-ai_langtorch&pullRequest=134&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=Knowly-ai_langtorch&pullRequest=134&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=Knowly-ai_langtorch&pullRequest=134&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=Knowly-ai_langtorch&pullRequest=134&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=Knowly-ai_langtorch&pullRequest=134&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=Knowly-ai_langtorch&pullRequest=134&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=Knowly-ai_langtorch&pullRequest=134&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=Knowly-ai_langtorch&pullRequest=134&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=Knowly-ai_langtorch&pullRequest=134&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=Knowly-ai_langtorch&pullRequest=134&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=Knowly-ai_langtorch&pullRequest=134&resolved=false&types=CODE_SMELL) [19 Code Smells](https://sonarcloud.io/project/issues?id=Knowly-ai_langtorch&pullRequest=134&resolved=false&types=CODE_SMELL)
> 
> [![0.0%](https://camo.githubusercontent.com/3f04cff3eeef8477afe696ae55c570cbb6ed02f16152497c14251828329a3e91/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f302d313670782e706e67)](https://sonarcloud.io/component_measures?id=Knowly-ai_langtorch&pullRequest=134&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=Knowly-ai_langtorch&pullRequest=134&metric=new_coverage&view=list) [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=Knowly-ai_langtorch&pullRequest=134&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=Knowly-ai_langtorch&pullRequest=134&metric=new_duplicated_lines_density&view=list)

Please resolve the code smell

2023-06-17 05:33 UTC, li2109 commented
A general approach to error handling:
use checked exceptions for conditions from which the caller can reasonably be expected to recover.
Use runtime exceptions to indicate programming errors.

2023-06-17 05:49 UTC, li2109 commented
Let's add comments for every public class

2023-06-17 07:02 UTC, li2109 requested changes

2023-06-18 09:51 UTC, AyoTheDev commented on src/main/java/ai/knowly/langtorch/store/vectordb/integration/pgvector/schema/PGVectorStoreSpec.java
> +    @Builder.Default private final String model = "text-embedding-ada-002";
Do you mean to create an EmbeddingModelConstants class that will contain String Constants like "text-embedding-ada-002"?

2023-06-18 10:24 UTC, AyoTheDev commented on src/main/java/ai/knowly/langtorch/store/vectordb/integration/pgvector/PGVectorStore.java
> +        }
We can't directly convert a float values to double

2023-06-20 08:15 UTC, AyoTheDev commented on src/main/java/ai/knowly/langtorch/store/vectordb/integration/pgvector/PGVectorStore.java
> +        return doubles;
We can't directly convert float values to double

2023-06-21 03:33 UTC, li2109 commented
Wow, the PR is well-documented!!!

2023-06-21 04:02 UTC, li2109 commented
IDK why some comments are left here https://github.com/AyoTheDev/langtorch/pull/1

2023-06-22 01:53 UTC, merged